weather:
  api:
    key: 6adf29405276de04c28203706e99fd56

spring:
  cache:
    type: caffeine
    cache-names: weather
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

logging:
  level:
    org:
      springframework:
        cache=DEBUG:
